<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_response extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'question_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'answer_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'answer_value' => array(
				'type' => 'VARCHAR',
				'constraint' => 140,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('response', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('response');
	}
}