<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_poll extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'name' => array(
				'type' => 'VARCHAR',
				'constraint' => 140,
			),
			'start_date' => array(
				'type' => 'DATE',
				'constraint' => 0,
			),
			'end_date' => array(
				'type' => 'DATE',
				'constraint' => 0,
			),
			'closed' => array(
				'type' => 'TINYINT',
				'constraint' => 1,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('poll', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('poll');
	}
}