<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Poll extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		 self::$relationships = array (
                        'question'          =>     ORM::has_many('\\Model\\Question')
						//'response'          =>     ORM::has_many('\\Model\\Response')
                );
		
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'name' => ORM::field('char[140]'),
			'start_date' => ORM::field('datetime'),
			'end_date' => ORM::field('datetime'),
			'closed' => ORM::field('numeric[1]'),
		);

	}
}