<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Question extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
			 self::$relationships = array (
                        'poll'          =>     ORM::belongs_to('\\Model\\Poll'),
                        'answer'          =>   ORM::has_many('\\Model\\Answer')
						//'response'			=> ORM::has_many('\\Model\\Response')
                );
		
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'poll_id' => ORM::field('int[11]'),
			'number' => ORM::field('int[11]'),
			'text' => ORM::field('char[500]'),
		);

	}
}