<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Response extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		
			/* self::$relationships = array (
                         'poll'          =>     ORM::has_one('\\Model\\Poll'),
                        'question'       =>     ORM::has_one('\\Model\\Question'),
						'response'       =>     ORM::has_one('\\Model\\Response')
                ); */
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'poll_id' => ORM::field('int[11]'),
			'question_id' => ORM::field('int[11]'),
			'answer_id' => ORM::field('int[11]'),
			'answer_value' => ORM::field('char[140]'),
		);

	}
}